# Generated by Django 4.1.1 on 2023-11-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="name",
        ),
    ]
